config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      put "like", to: "images#upvote"
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'welcome#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, :except => [:index, :show, :upvote]
  def upvote
    @image.upvote_by current_user
    redirect_to :back
  end

  # GET /images
  # GET /images.json
  def index
    @images = Image.all.order("created_at DESC")
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
  
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    if user_signed_in?
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  else
 flash[:notice] = "yd"
  redirect_to action: "index"
  end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    if user_signed_in?
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  else
redirect_to action: "index"
    flash[:notice] = "yp"
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
 def new
    redirect_to root_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { multipart: true ,:class => "form-horizontal image" } do |f| %>

  <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture,accept:'image/jpeg, image/png, image/jpg' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>
 

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<% @images = Image.all %>
<% @images.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |pic| %>
      <div class='col-md-3'>
        <%= link_to((image_tag pic.picture.url, class: "img-responsive"), pic) %>
        <h3><%= pic.name %></h3>
      </div>
    <% end %>
  </div>
<% end %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.haml
#pic_show.row
  .col-md-12.col-md-offset-3
    .panel.panel-default
      .panel-heading.pic_image
        = image_tag @image.picture.url
      .panel-body
        %h1= @image.name
      .panel-footer
        .row
          .col-md-6
            %p.user
              By
              = @image.user.email
          .col.md-6
            .btn-group.pull-right
              = link_to like_image_path(@image), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                = @image.get_upvotes.size
                
                
              -if user_signed_in?
                = link_to "Edit", edit_image_path, class: "btn btn-info"
                = link_to "Delete", image_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SwissOud" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <%= link_to('SwissOud', root_path, class: 'navbar-brand', title: 'SwissOud')  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
             <% if user_signed_in? %>
          <li><%= link_to('New Picture', new_image_path, title: 'New Picture', :method => :get) %></li>
          <li><%= link_to('Edit Profile', edit_user_registration_path, title: 'Edit profile', :method => :get) %></li>
            <li><%= link_to('Photos', images_path , title: 'Photos', :method => :get) %></li>
             <% else %>
            <li><%= link_to('Photos', images_path, class: 'btn btn-xs btn', title: 'Photos', :method => :get) %></li>

            <li><%= link_to "About us", "/path2"  %></li>
            <li><%= link_to "Contact us", "/path3"  %></li>
            <% end %>

              <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">en <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">de</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">ar</a></li>
          </ul>
        </li>
      
       <% if user_signed_in? %>
          <li><%= link_to('logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'logout', :method => :delete) %></li>
        <% else %>
        <li><%= link_to('login', new_user_session_path, title: 'login', :method => :get) %></li>

        <% end %>
      </ul>
        </div>
        
      </div>
      
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>